tabela = ('SANTOS','FLAMENGO','PALMEIRAS','ATLETICO MG','CORINTHIANS','INTERNACIONAL','SAO PAULO','ATLETICO PR','BOTAFOGO','CEARA','BAHIA','GREMIO','FORTALEZA','GOIAS','VASCO','FLUMINENSE','CRUZEIRO','CHAPECOENSE','CSA','AVAI')
print(tabela)
print(tabela[0:5])
print(tabela[-4:])
print(sorted(tabela))
print(tabela.index('CHAPECOENSE')+ 1)